server.port=8080
server.servlet.context-path=/api

spring.application.name=smartattend-backend

# PostgreSQL datasource
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/smartattend}
spring.datasource.username=postgres
spring.datasource.password=qusa3187
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET:c21hcnRhdHRlbmRTdXBlclNlY3JldEtleUZvckpXVFNpZ25pbmcyMDI2ISE=}
jwt.expiration-ms=86400000

logging.level.org.springframework.security=INFO
logging.level.com.smartattend=DEBUG
